spring:
  application:
    name: wms-organic

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organicdb
    username: tcat
    password: 1111
  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
